default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DB_USERNAME") { 'postgres' } %>
  password: <%= ENV.fetch("DB_PASSWORD") { 'postgres' } %>
  host: <%= ENV.fetch("DB_HOST") { 'localhost' } %>
  port: 5432

# TODO: change databse names here as well
development:
  <<: *default
  database: the_pond_project_development

test:
  <<: *default
  database: the_pond_project_test

staging:
  <<: *default
  database: the_pond_project_staging

production:
  <<: *default
  database: the_pond_project_prod